# Generated by Django 4.1.1 on 2022-10-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_remove_notification_notification_types'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='notification_type',
            field=models.ManyToManyField(to='notifications.notificationtype'),
        ),
    ]
