# Generated by Django 4.1.1 on 2022-10-24 21:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_type', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_task_type', models.CharField(max_length=45)),
                ('text', models.TextField(max_length=350)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('notification_date', models.DateField(default=datetime.datetime.now)),
                ('notification_time', models.TimeField(default=datetime.datetime.now)),
                ('notification_periodicity', models.BooleanField(default=False)),
                ('notification_periodicity_num', models.IntegerField(default=1)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_time'],
            },
        ),
    ]
