# Generated by Django 4.1.1 on 2022-10-10 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotificationcategories',
            name='user_notification_category_color',
            field=models.CharField(max_length=10),
        ),
    ]
