# Generated by Django 4.1.1 on 2022-10-27 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtype',
            name='color',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
