# Generated by Django 4.1.1 on 2022-12-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationstatus',
            name='time_stamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
