# Generated by Django 4.1.1 on 2022-12-11 12:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notificationstatus_time_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationperiodicity',
            name='notification_type_periodicity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.notificationbase'),
        ),
        migrations.AlterField(
            model_name='notificationsingle',
            name='notification_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Дата исполнения'),
        ),
        migrations.AlterField(
            model_name='notificationsingle',
            name='notification_status',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='notifications.notificationstatus', verbose_name='Выполнено'),
        ),
        migrations.AlterField(
            model_name='notificationsingle',
            name='notification_time',
            field=models.TimeField(default=datetime.datetime.now, verbose_name='Время исполнения'),
        ),
        migrations.AlterField(
            model_name='notificationsingle',
            name='notification_type_single',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.notificationbase'),
        ),
    ]
