# Generated by Django 4.1.1 on 2022-10-27 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationtype_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_color',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
