# Generated by Django 4.1.1 on 2022-10-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_task_type',
            field=models.CharField(choices=[], max_length=30),
        ),
    ]
