# Generated by Django 4.1.1 on 2022-10-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_notification_task_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationtype',
            name='user',
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_types',
            field=models.ManyToManyField(to='notifications.notificationtype'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_task_type',
            field=models.CharField(choices=[(1, 1), (1, 1), (1, 1)], max_length=30),
        ),
    ]
