# Generated by Django 4.1.1 on 2022-10-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_notification_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_color',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_task_type',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
