# Generated by Django 4.1.1 on 2022-11-15 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notificationtype_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_task_type',
            field=models.ForeignKey(default='general', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_task_type', to='notifications.notificationtype'),
        ),
    ]
