# Generated by Django 4.1.1 on 2022-11-27 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_notification_task_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['user', '-created_time']},
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_task_type',
            field=models.ForeignKey(default='study', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_task_type', to='notifications.notificationtype'),
        ),
    ]
