# Generated by Django 4.1.1 on 2022-12-16 16:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notificationperiodicity_frequency_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationsingle',
            name='notification_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 16, 16, 53, 10, 89633), verbose_name='Дата исполнения'),
        ),
        migrations.AlterField(
            model_name='notificationsingle',
            name='notification_time',
            field=models.TimeField(default=datetime.datetime(2022, 12, 16, 16, 53, 10, 89643), verbose_name='Время исполнения'),
        ),
    ]
