# Generated by Django 4.1.1 on 2022-10-14 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_remove_notificationtype_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='notification_task_type',
        ),
    ]
