# Generated by Django 4.1.1 on 2022-10-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_remove_notification_notification_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_task_type',
            field=models.CharField(default=1, max_length=45),
            preserve_default=False,
        ),
    ]
