# Generated by Django 4.1.1 on 2022-12-18 11:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_notificationsingle_notification_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationsingle',
            name='notification_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 18, 11, 35, 34, 74569), verbose_name='Дата исполнения'),
        ),
        migrations.AlterField(
            model_name='notificationsingle',
            name='notification_time',
            field=models.TimeField(default=datetime.datetime(2022, 12, 18, 11, 35, 34, 74581), verbose_name='Время исполнения'),
        ),
    ]
