# Generated by Django 4.1.1 on 2022-12-05 13:35

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPeriodicity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_periodicity_num', models.IntegerField(default=1)),
                ('frequency_hours', models.IntegerField(choices=[(1, 1), (4, 4), (12, 12), (24, 24)], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)])),
                ('frequency_days', models.IntegerField(choices=[(1, 1), (4, 4), (15, 15), (28, 28)], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)])),
                ('frequency_months', models.IntegerField(choices=[(1, 1), (3, 3), (6, 6), (12, 12)], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
            ],
        ),
        migrations.CreateModel(
            name='NotificationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notification_date',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notification_periodicity',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notification_periodicity_num',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notification_task_type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notification_time',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='text',
        ),
        migrations.CreateModel(
            name='NotificationBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=350)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('notification_date', models.DateField(default=datetime.datetime.now)),
                ('notification_time', models.TimeField(default=datetime.datetime.now)),
                ('notification_status', models.ManyToManyField(to='notifications.notificationstatus')),
                ('notification_task_type', models.ForeignKey(default='study', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_task_type', to='notifications.notificationtype')),
                ('notification_type_periodicity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notifications.notificationperiodicity')),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='notifications',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.notificationbase'),
        ),
    ]
