# Generated by Django 4.1.1 on 2022-10-14 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_notification_notification_task_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='notification_types',
        ),
    ]
