# Generated by Django 4.1.1 on 2022-12-07 14:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_remove_notificationbase_notification_type_periodicity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='notification_type_periodicity',
        ),
        migrations.AddField(
            model_name='notificationbase',
            name='notification_type_periodicity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.notificationperiodicity'),
        ),
        migrations.AlterField(
            model_name='notificationperiodicity',
            name='frequency_days',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (5, 5), (15, 15), (28, 28)], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)]),
        ),
        migrations.AlterField(
            model_name='notificationperiodicity',
            name='frequency_hours',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (5, 5), (12, 12), (24, 24)], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)]),
        ),
    ]
