# Generated by Django 4.1.1 on 2022-12-18 11:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_alter_notificationsingle_notification_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationsingle',
            name='notification_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата исполнения'),
        ),
        migrations.AlterField(
            model_name='notificationsingle',
            name='notification_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Время исполнения'),
        ),
    ]
