# Generated by Django 4.1.1 on 2022-12-18 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_alter_notificationsingle_notification_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationsingle',
            name='notification_type_single',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_single', to='notifications.notificationbase'),
        ),
    ]
