# Generated by Django 4.1.1 on 2022-12-18 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_alter_notificationsingle_notification_type_single'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationperiodicity',
            name='notification_type_periodicity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_periodic', to='notifications.notificationbase'),
        ),
    ]
